// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oravity.Infrastructure.Database;

#nullable disable

namespace Oravity.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330144843_AddPatientTable")]
    partial class AddPatientTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Branch", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("tr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("VerticalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("VerticalId");

                    b.ToTable("branches", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Company", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DefaultLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("tr");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("SubscriptionEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("VerticalId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("VerticalId");

                    b.ToTable("companies", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasDefaultValue("ltr");

                    b.Property<string>("FlagEmoji")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NativeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("languages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "tr",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "ltr",
                            FlagEmoji = "🇹🇷",
                            IsActive = true,
                            IsDefault = true,
                            IsDeleted = false,
                            Name = "Türkçe",
                            NativeName = "Türkçe",
                            PublicId = new Guid("00000001-0000-0000-0000-000000000001"),
                            SortOrder = 0
                        },
                        new
                        {
                            Id = 2L,
                            Code = "en",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "ltr",
                            FlagEmoji = "🇬🇧",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "İngilizce",
                            NativeName = "English",
                            PublicId = new Guid("00000001-0000-0000-0000-000000000002"),
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ar",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "rtl",
                            FlagEmoji = "🇸🇦",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Arapça",
                            NativeName = "العربية",
                            PublicId = new Guid("00000001-0000-0000-0000-000000000003"),
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 4L,
                            Code = "ru",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "ltr",
                            FlagEmoji = "🇷🇺",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Rusça",
                            NativeName = "Русский",
                            PublicId = new Guid("00000001-0000-0000-0000-000000000004"),
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 5L,
                            Code = "de",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Direction = "ltr",
                            FlagEmoji = "🇩🇪",
                            IsActive = true,
                            IsDefault = false,
                            IsDeleted = false,
                            Name = "Almanca",
                            NativeName = "Deutsch",
                            PublicId = new Guid("00000001-0000-0000-0000-000000000005"),
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.LoginAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Identifier", "CreatedAt")
                        .HasDatabaseName("ix_login_attempts_identifier_created");

                    b.ToTable("login_attempts", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.OutboxMessage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer");

                    b.Property<DateTime>("NextRetryAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextRetryAt")
                        .HasDatabaseName("ix_outbox_pending")
                        .HasFilter("\"Status\" IN (1, 3)");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Patient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BloodType")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<long>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("CreatedByUserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("PreferredLanguageCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("tr");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("TcNumberEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TcNumberHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("UpdatedByUserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_patients_public_id");

                    b.HasIndex("TcNumberHash")
                        .HasDatabaseName("ix_patients_tc_hash");

                    b.HasIndex("BranchId", "Phone")
                        .HasDatabaseName("ix_patients_branch_phone");

                    b.HasIndex("BranchId", "LastName", "FirstName")
                        .HasDatabaseName("ix_patients_branch_name");

                    b.ToTable("patients", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Permission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDangerous")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Resource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_tokens_hash");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RoleTemplate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("role_templates", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "BRANCH_MANAGER",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Şube içindeki tüm işlemleri yönetir",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Şube Yöneticisi",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            Id = 2L,
                            Code = "DOCTOR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Klinik muayene ve tedavi işlemlerini yürütür",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Hekim",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            Id = 3L,
                            Code = "ASSISTANT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Hekime yardımcı klinik personel",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Asistan",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            Id = 4L,
                            Code = "RECEPTIONIST",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Randevu ve hasta kayıt işlemlerini yönetir",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Resepsiyonist",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ACCOUNTANT",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mali işlemler ve raporlama",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Muhasebeci",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            Id = 6L,
                            Code = "READONLY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Yalnızca görüntüleme yetkisi",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Salt Okunur",
                            PublicId = new Guid("00000003-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RoleTemplatePermission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleTemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleTemplateId", "PermissionId")
                        .IsUnique();

                    b.ToTable("role_template_permissions", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPlatformAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreferredLanguageCode")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.UserPermissionOverride", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsGranted")
                        .HasColumnType("boolean");

                    b.Property<long>("PermissionId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("UserId");

                    b.ToTable("user_permission_overrides", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.UserRoleAssignment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("BranchId")
                        .HasColumnType("bigint");

                    b.Property<long?>("CompanyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<long>("RoleTemplateId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("RoleTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("user_role_assignments", (string)null);
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Vertical", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyChartType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("DefaultModules")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<bool>("HasBodyChart")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PatientLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Hasta");

                    b.Property<string>("ProviderLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Hekim");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("RequiresKts")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("TreatmentLabel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Tedavi");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("verticals", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BodyChartType = "DENTAL_FDI",
                            Code = "DENTAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "FINANCE", "APPOINTMENT", "TREATMENT" },
                            HasBodyChart = true,
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Diş Hekimliği",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Hekim",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000001"),
                            RequiresKts = true,
                            SortOrder = 0,
                            TreatmentLabel = "Tedavi"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "AESTHETIC",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = false,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Estetik & Güzellik",
                            PatientLabel = "Müşteri",
                            ProviderLabel = "Uzman",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000002"),
                            RequiresKts = false,
                            SortOrder = 1,
                            TreatmentLabel = "Uygulama"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "NUTRITION",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = false,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Diyetisyen",
                            PatientLabel = "Danışan",
                            ProviderLabel = "Diyetisyen",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000003"),
                            RequiresKts = false,
                            SortOrder = 2,
                            TreatmentLabel = "Seans"
                        },
                        new
                        {
                            Id = 4L,
                            BodyChartType = "HAIR_MAP",
                            Code = "HAIR",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = true,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Saç Ekim",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Uzman",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000004"),
                            RequiresKts = false,
                            SortOrder = 3,
                            TreatmentLabel = "Operasyon"
                        },
                        new
                        {
                            Id = 5L,
                            BodyChartType = "BODY_REGION",
                            Code = "PODOLOGY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = true,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Ayak Bakımı",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Podolog",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000005"),
                            RequiresKts = false,
                            SortOrder = 4,
                            TreatmentLabel = "Uygulama"
                        },
                        new
                        {
                            Id = 6L,
                            BodyChartType = "BODY_REGION",
                            Code = "PHYSIO",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = true,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Fizik Tedavi",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Fizyoterapist",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000006"),
                            RequiresKts = true,
                            SortOrder = 5,
                            TreatmentLabel = "Seans"
                        },
                        new
                        {
                            Id = 7L,
                            Code = "PSYCHOLOGY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = false,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Psikoloji",
                            PatientLabel = "Danışan",
                            ProviderLabel = "Terapist",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000007"),
                            RequiresKts = false,
                            SortOrder = 6,
                            TreatmentLabel = "Seans"
                        },
                        new
                        {
                            Id = 8L,
                            Code = "VETERINARY",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = false,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Veteriner",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Veteriner",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000008"),
                            RequiresKts = false,
                            SortOrder = 7,
                            TreatmentLabel = "Tedavi"
                        },
                        new
                        {
                            Id = 9L,
                            Code = "GENERAL",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            DefaultModules = new[] { "CORE", "APPOINTMENT" },
                            HasBodyChart = false,
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Genel Muayenehane",
                            PatientLabel = "Hasta",
                            ProviderLabel = "Hekim",
                            PublicId = new Guid("00000002-0000-0000-0000-000000000009"),
                            RequiresKts = true,
                            SortOrder = 8,
                            TreatmentLabel = "Muayene"
                        });
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Branch", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Company", "Company")
                        .WithMany("Branches")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Oravity.SharedKernel.Entities.Vertical", "Vertical")
                        .WithMany("Branches")
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Company", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Vertical", "Vertical")
                        .WithMany("Companies")
                        .HasForeignKey("VerticalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Vertical");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Patient", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RefreshToken", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RoleTemplatePermission", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Permission", "Permission")
                        .WithMany("RoleTemplatePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oravity.SharedKernel.Entities.RoleTemplate", "RoleTemplate")
                        .WithMany("RoleTemplatePermissions")
                        .HasForeignKey("RoleTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("RoleTemplate");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.UserPermissionOverride", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Oravity.SharedKernel.Entities.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Oravity.SharedKernel.Entities.Permission", "Permission")
                        .WithMany("UserPermissionOverrides")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Oravity.SharedKernel.Entities.User", "User")
                        .WithMany("PermissionOverrides")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.UserRoleAssignment", b =>
                {
                    b.HasOne("Oravity.SharedKernel.Entities.Branch", "Branch")
                        .WithMany("UserRoleAssignments")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Oravity.SharedKernel.Entities.Company", "Company")
                        .WithMany("UserRoleAssignments")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Oravity.SharedKernel.Entities.RoleTemplate", "RoleTemplate")
                        .WithMany("UserRoleAssignments")
                        .HasForeignKey("RoleTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Oravity.SharedKernel.Entities.User", "User")
                        .WithMany("RoleAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Company");

                    b.Navigation("RoleTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Branch", b =>
                {
                    b.Navigation("UserRoleAssignments");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Company", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("UserRoleAssignments");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Permission", b =>
                {
                    b.Navigation("RoleTemplatePermissions");

                    b.Navigation("UserPermissionOverrides");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.RoleTemplate", b =>
                {
                    b.Navigation("RoleTemplatePermissions");

                    b.Navigation("UserRoleAssignments");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.User", b =>
                {
                    b.Navigation("PermissionOverrides");

                    b.Navigation("RoleAssignments");
                });

            modelBuilder.Entity("Oravity.SharedKernel.Entities.Vertical", b =>
                {
                    b.Navigation("Branches");

                    b.Navigation("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
